### ISSUE TITLE
Guidance on Localizing Areas of Interest in New Scenes Using Notebook Scripts

### ISSUE THREAD

**Issue by XinYu-Andy** [orig333/Blended-NeRF#3]
Hello,

I'm seeking clarification on how to effectively utilize the scripts provided in the notebooks for locating specific regions of interest in new scenes. I'm particularly puzzled by the `create_box` function's adjustable parameters, namely `zoom`, `box_center`, and `edge_size`.

Despite keeping other parameters constant and only altering one at a time, the resulting visualizations display substantial changes in the image itself, not just the position of the box. This has led to some confusion on my part as I'm trying to isolate the exact area I'm interested in within the scene.

Could you please provide some insights or documentation on how these parameters interact with the scene and any recommended steps for adjusting them to pinpoint a desired region?

Thank you for your assistance.

**Comment by orig333** [comment]
Hi,
You first need to make sure you are using the correct notebook for your scene.
Regarding the parameters:
1. zoom - Controls the distance of the camera from the box center.
2. box_center - The 3d center of the box, changing its values will change the location of the box in the scene.
3. edge size -  Determines the size of the box in each dimension which in turn will determine the size of the box. 

To get some intuition, I suggest to
 1. Start with the boxes we provide for the scenes.
 2. Print its coordinates.
 3. Compute from the box coordinates the box center and the edges size for each dimension. 
 4. Using these value as a starting point. 
 
Thank you for your interest in our work.

**Comment by XinYu-Andy** [comment]
> Hi, You first need to make sure you are using the correct notebook for your scene. Regarding the parameters:
> 
> 1. zoom - Controls the distance of the camera from the box center.
> 2. box_center - The 3d center of the box, changing its values will change the location of the box in the scene.
> 3. edge size -  Determines the size of the box in each dimension which in turn will determine the size of the box.
> 
> To get some intuition, I suggest to
> 
> 1. Start with the boxes we provide for the scenes.
> 2. Print its coordinates.
> 3. Compute from the box coordinates the box center and the edges size for each dimension.
> 4. Using these value as a starting point.
> 
> Thank you for your interest in our work.


Thank you for your response. I'd like to know if this means that the camera pose will change with the adjustments of `zoom` and `center`? I see there is an option to `set_pose` already. But if the pose itself changes with these two parameters, it seems challenging to control. Also, could you clarify whether the `center` is in the image coordinate system or in the world coordinate system?

**Comment by XinYu-Andy** [comment]
I am currently working on placing a bounding box in a new scene. I want the bounding box to be at a specific location I designate, but adjusting those parameters is quite challenging. For example, the first image below is the scene when I set the parameters to zoom=0.5, box_center_x = box_center_y = box_center_z = -0.7, edge_size_x = edge_size_y = edge_size_z = 0.3, pose_index = 0. When I simply change box_center_x to 0, I get the second image below. As you can see, in addition to the movement of the box, the pose of the entire scene that is visible has also changed. This is indeed difficult to control. Do you have any good suggestions? For instance, if I want to place the box on the bench in the scene.


The first image:
<img width="732" alt="image" src="https://github.com/orig333/Blended-NeRF/assets/60741299/c69a1b8a-f621-49ec-85e8-4b9e573e93e3">

The second image:
<img width="723" alt="image" src="https://github.com/orig333/Blended-NeRF/assets/60741299/b99b45b3-c0c9-43ed-bff7-a545dcd64406">

**Comment by orig333** [comment]
The rays from the camera are centered around the center of the box.
Note that indeed, your closer to the origin in the x axis(x=red,y=green,z=blue). 
My suggestion is to try another camera pose, i.e. different pose_index.
For more intuition, note that in llff the trajectory of the camera is a spiral curve:
[spiral curve](https://christopherchudzicki.github.io/MathBox-Demos/parametric_curves_3D.html?settings=eyJmdW5jdGlvbnMiOnsiYSI6eyJ5IjoiLTMqc2luKHQpIiwieiI6Ii0zKnNpbigwLjUqdCkiLCJ0Ijo4Ljc2OTk5OTk5OTk5OTg1NywidE1heCI6MTIuNn19LCJjb250YWluZXJJZCI6Im15LW1hdGgtYm94IiwiY2FtZXJhIjp7InBvc2l0aW9uIjpbMS4xNiwwLjUsMS4wMV19LCJub1pvb20iOnRydWUsImZvY3VzIjoxLjY5NTU4MjQ5NTc4MTMxN30=).

If you want the box to be on the bench, I suggest that you start from a box center located in the origin of the scene which is slightly above the bench and than use the axis for intuition on how to move the box further.
