### ISSUE TITLE
Configurations for Object Insertion or Replacement in 360-degree Scenes

### ISSUE THREAD

**Issue by XinYu-Andy** [orig333/Blended-NeRF#4]
Hello! In the config for 360-degree scenes, it seems that the primary focus is on editing. If I want to perform object insertion or replacement, do you have any recommendations for changing the config? I've noticed there are many parameters related to loss and other weights. Can I directly copy the relevant parameters from the `fern.txt` config file?

**Comment by orig333** [comment]
You need to make sure that the change_color parameter is set to false (or just remove it from the config file).
Other than that, the main parameters that controls the edit are the max_trans, the sample_scale and the description of course. But there are other parameters you can tweak and play with so read carefully the help argument for the different parameters in the config_parser function.

**Comment by Frank-Zhou-01** [comment]
Excuse me! I would like to ask you about the 4 24GB A5000 graphics cards in your paper. My computing power does not meet this requirement, so I would like to ask how much computing power is required to run this model. Thank you!

**Comment by orig333** [comment]
Hi @Frank-Zhou-01,
You can try and run with lower computing power by playing with the parameters below:
1. chunk.
2. netchunk.
3. N_samples.
4. N_importance.
5. sample_scale.

Information regarding each of these parameters can be find in config_parser function in run_BlendedNeRF.py.

Of course, changing any of the following parameters can affect the running time or the quality of the final result.

**Comment by Frank-Zhou-01** [comment]
Thank you very much for your answer. I have obtained some experimental results by modifying some parameters. I am now using a more advanced graphics card for computation. I wish you success in your work and good health!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "orig333/Blended-NeRF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月26日(星期天) 凌晨2:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [orig333/Blended-NeRF] Configurations for Object Insertion or Replacement in 360-degree Scenes (Issue #4)





 
Hi @Frank-Zhou-01,
 You can try and run with lower computing power by playing with the parameters below:
  
chunk.
 
netchunk.
 
N_samples.
 
N_importance.
 
sample_scale.
  
Information regarding each of these parameters can be find in config_parser function in run_BlendedNeRF.py.
 
Of course, changing any of the following parameters can affect the running time or the quality of the final result.
